object Versions {
    const val easypermission = "3.0.0"
    const val navigation_fragment_ktx = "2.3.0"
    const val activity_ktx = "1.1.0"
    const val hilt_lifecycle_viewmodel = "1.0.0-alpha02"
    const val hilt_compiler = "1.0.0-alpha02"
    const val hilt_android = "2.28-alpha"
    const val coroutines = "1.3.5"
    const val logging_interceptor: String = "3.12.0"
    const val converter_gson: String = "2.5.0"
    const val gson: String = "2.8.5"
    const val retrofit: String = "2.6.0"
    const val room = "2.2.3"
    const val navigation = "2.3.2"
    const val kotlin = "1.3.72"
    const val core = "1.3.2"
    const val appcompat = "1.2.0"
    const val material = "1.2.1"
    const val constraintlayout = "2.0.4"
    const val lifecycle = "2.2.0"
    const val junit = "4.+"
    const val test_ext = "1.1.2"
    const val espreso_core = "3.3.0"
    const val gradle = "4.1.1"
    const val mapbox = "9.2.0"
    const val mapbox_navigation = "0.42.6"

}